#ifndef _FUNCTIONS_H_
#define _FUNCTIONS_H_

#include "Types.h"
#define STR struct
Program* make_Program_op0(STR GlobalStmtList* _globalStmtList);
GlobalStmtList* make_GlobalStmtList_op0(STR GlobalStmtList* _globalStmtList, STR GlobalStmt* _globalStmt);
GlobalStmtList* make_GlobalStmtList_op1(STR GlobalStmt* _globalStmt);
GlobalStmt* make_GlobalStmt_op0(STR DeclFun* _declFun);
GlobalStmt* make_GlobalStmt_op1(STR DefFun* _defFun, STR Error* _error);
GlobalStmt* make_GlobalStmt_op2(STR DefFun* _defFun);
GlobalStmt* make_GlobalStmt_op3(STR DeclVar* _declVar);
GlobalStmt* make_GlobalStmt_op4(STR DeclVar* _declVar, STR Error* _error);
GlobalStmt* make_GlobalStmt_op5(STR AttrVar* _attrVar);
GlobalStmt* make_GlobalStmt_op6(STR Block* _block);
DefFun* make_DefFun_op0(STR BaseType* _baseType, Id* __v_id, STR ParamListVoid* _paramListVoid, STR Block* _block);
DeclFun* make_DeclFun_op0( STR BaseType* _baseType, Id* __v_id, STR ParamListVoid* _paramListVoid);
DeclVar* make_DeclVar_op0(MatType* __mat_type, STR BaseType* _baseType, Id* __v_id,  STR Num* _num0,  STR Num* _num1);
DeclVar* make_DeclVar_op1(STR BaseType* _baseType, STR IdArr* _idArr);
IdArr* make_IdArr_op0(Id* _id,  STR NumId* _numId);
IdArr* make_IdArr_op1(Id* _id);
AttrVar* make_AttrVar_op0(STR MatAttr* _matAttr);
AttrVar* make_AttrVar_op1(STR IndexAttr* _indexAttr);
AttrVar* make_AttrVar_op2(STR SimpleAttr* _simpleAttr);
SimpleAttr* make_SimpleAttr_op0(Id* _id, STR Expr* _expr);
IndexAttr* make_IndexAttr_op0(Id* _id,  STR NumId* _numId, STR Expr* _expr);
MatAttr* make_MatAttr_op0(Id* _id,  STR NumListList* _numListList);
MatAttr* make_MatAttr_op1(Id* _id,  STR NumId* _numId,  STR NumList* _numList);
MatAttr* make_MatAttr_op2(Id* _id,  STR NumId* _numId0,  STR NumId* _numId1, STR Expr* _expr);
NumListList* make_NumListList_op0(STR NumListList* _numListList,  STR NumList* _numList);
NumListList* make_NumListList_op1(STR NumList* _numList);
NumList* make_NumList_op0(STR NumList* _numList, STR Num* _num);
NumList* make_NumList_op1(STR Num* _num);
NumList* make_NumList_op2(Id* _id);
Stmt* make_Stmt_op0(STR Expr* _expr);
Stmt* make_Stmt_op1(Id* _id, Id* __v_id1);
Stmt* make_Stmt_op2( Id* __v_id,  STR NumId* _numId0,  STR NumId* _numId1);
Stmt* make_Stmt_op3( Id* __v_id,  STR NumId* _numId);
Stmt* make_Stmt_op4( Id* __v_id);
Stmt* make_Stmt_op5(STR Expr* _expr);
Stmt* make_Stmt_op6(STR Call* _call);
Stmt* make_Stmt_op7(STR DeclVar* _declVar);
Stmt* make_Stmt_op8(STR AttrVar* _attrVar);
Stmt* make_Stmt_op9(STR FlowControl* _flowControl);
Stmt* make_Stmt_op10(STR Loop* _loop);
ParamListVoid* make_ParamListVoid_op0();
ParamListVoid* make_ParamListVoid_op1(STR ParamList* _paramList);
ParamList* make_ParamList_op0(STR ParamList* _paramList, STR Param* _param);
ParamList* make_ParamList_op1(STR Param* _param);
Param* make_Param_op0(STR BaseType* _baseType, Id* __v_id);
Param* make_Param_op1(MatType* __mat_type, STR BaseType* _baseType, Id* __v_id);
Loop* make_Loop_op0( STR Expr* _expr, STR Block* _block);
FlowControl* make_FlowControl_op0(STR Expr* _expr, STR Block* _block,  STR FlowControl* _flowControl);
FlowControl* make_FlowControl_op1(STR Expr* _expr, STR Block* _block0,  STR Block* _block1);
FlowControl* make_FlowControl_op2(STR Error* _error, STR Block* _block0,  STR Block* _block1);
FlowControl* make_FlowControl_op3(STR Expr* _expr, STR Error* _error, STR Block* _block0,  STR Block* _block1);
Block* make_Block_op0( STR StmtList* _stmtList);
Block* make_Block_op1();
StmtList* make_StmtList_op0(STR StmtList* _stmtList, STR Stmt* _stmt);
StmtList* make_StmtList_op1(STR Stmt* _stmt);
Expr* make_Expr_op0(STR AddExpr* _addExpr0, STR Relop* _relop, STR AddExpr* _addExpr1);
Expr* make_Expr_op1(STR AddExpr* _addExpr);
Relop* make_Relop_op0();
Relop* make_Relop_op1();
Relop* make_Relop_op2();
Relop* make_Relop_op3();
Relop* make_Relop_op4();
Relop* make_Relop_op5();
AddExpr* make_AddExpr_op0(STR AddExpr* _addExpr, STR Addop* _addop, STR Term* _term);
AddExpr* make_AddExpr_op1(STR Term* _term);
Addop* make_Addop_op0();
Addop* make_Addop_op1();
Term* make_Term_op0(STR Term* _term, STR Mulop* _mulop, STR Bin* _bin);
Term* make_Term_op1(STR Bin* _bin);
Mulop* make_Mulop_op0();
Mulop* make_Mulop_op1();
Mulop* make_Mulop_op2();
Mulop* make_Mulop_op3();
Bin* make_Bin_op0(STR Bin* _bin, STR BinLogi* _binLogi, STR Unary* _unary);
Bin* make_Bin_op1(STR Unary* _unary);
BinLogi* make_BinLogi_op0();
BinLogi* make_BinLogi_op1();
Unary* make_Unary_op0(STR UnaryOp* _unaryOp, STR Factor* _factor);
Unary* make_Unary_op1(STR Factor* _factor);
UnaryOp* make_UnaryOp_op0();
UnaryOp* make_UnaryOp_op1();
Factor* make_Factor_op0(STR Expr* _expr);
Factor* make_Factor_op1(STR Aux* _aux);
Factor* make_Factor_op2(STR Call* _call);
Factor* make_Factor_op3(STR Ascii* _ascii);
Aux* make_Aux_op0(Id* _id,  STR Expr* _expr0,  STR Expr* _expr1);
Aux* make_Aux_op1(Id* _id,  STR Expr* _expr);
Aux* make_Aux_op2(STR NumId* _numId);
NumId* make_NumId_op0(STR Num* _num);
NumId* make_NumId_op1(Id* _id);
Call* make_Call_op0(Id* _id, STR ArgList* _argList);
Call* make_Call_op1(Id* _id); 
ArgList* make_ArgList_op0(STR ArgList* _argList, STR Arg* _arg);
ArgList* make_ArgList_op1(STR Arg* _arg);
Arg* make_Arg_op0(STR MatArg* _matArg);
Arg* make_Arg_op1(STR Aux* _aux);
MatArg* make_MatArg_op0(Id* _id, STR NumId* _numId0, STR NumId* _numId1);
Ascii* make_Ascii_op0(Ascii* _ascii);
BaseType* make_BaseType_op0();
BaseType* make_BaseType_op1();
BaseType* make_BaseType_op2();
Num* make_Num_op0(float fval);
Num* make_Num_op1(int ival);

#endif